using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace No_Kill_Inventory.Migrations
{
    /// <inheritdoc />
    public partial class AutoGenerateData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "b74ddd14-6340-4840-95c2-db12554843e5",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "b83bd6ff-d0f6-4bc1-8174-a0d677488ca0", "AQAAAAIAAYagAAAAEDkeBrjsTK3Zi+7EID4KQHJW+s/j02Km3OwmzmoNwG7Mq8UySVIwC07F2jFF9Aeo4Q==", "487e0faf-3bb3-4b60-85d3-d3af35a9bed4" });

            migrationBuilder.InsertData(
                table: "CatItems",
                columns: new[] { "ItemID", "Type", "Weight" },
                values: new object[,]
                {
                    { 1, "Adult", 0 },
                    { 2, "Kitty", 0 },
                    { 3, "Wet", 0 },
                    { 4, "Special", 0 }
                });

            migrationBuilder.InsertData(
                table: "DogItems",
                columns: new[] { "ItemID", "Type", "Weight" },
                values: new object[,]
                {
                    { 1, "Adult", 0 },
                    { 2, "Puppy", 0 },
                    { 3, "Weight Control", 0 },
                    { 4, "Grain Free", 0 },
                    { 5, "Small Bites", 0 },
                    { 6, "Wet", 0 },
                    { 7, "Special", 0 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "CatItems",
                keyColumn: "ItemID",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "CatItems",
                keyColumn: "ItemID",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "CatItems",
                keyColumn: "ItemID",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "CatItems",
                keyColumn: "ItemID",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "DogItems",
                keyColumn: "ItemID",
                keyValue: 7);

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "b74ddd14-6340-4840-95c2-db12554843e5",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "5644d6d9-862c-4aac-9f49-403d63d56fcd", "AQAAAAIAAYagAAAAEAuSLGd98m3qT4ErF9D3lAOOy3FlPj1GKevfZqdvadHG8lYt/smyMwuXMHu8KUoVfg==", "632097d3-704e-4b2d-9e85-1a5ba5b5dd9b" });
        }
    }
}
